name: flutter_colorful_search
description: "A lightweight Flutter widget to highlight matching text segments within a string using customizable colorful styles — perfect for search and autocomplete UIs."
version: 1.0.0
homepage: https://github.com/raihansikdar/flutter_colorful_search
repository: https://github.com/raihansikdar/flutter_colorful_search

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.15

